{
    "name": "Trailer Inspection - SASO",
    "version": "19.0.3.0.4",
    "category": "Operations/Inspections",
    "summary": "Trailer and semi-trailer inspections against SASO requirements",
    "description": """
Manage trailer and semi-trailer inspections, controlled requirement revisions,
evidence, calibrated equipment, independent technical review, nonconformities,
and bilingual inspection reports.
    """,
    "author": "ClickBuild",
    "website": "https://odoo.clickbulid.com",
    "depends": ["base", "mail", "web"],
    "data": [
        "security/trailer_inspection_security.xml",
        "security/ir.model.access.csv",
        "data/trailer_inspection_sequence.xml",
        "data/trailer_standard_data.xml",
        "data/trailer.inspection.requirement.csv",
        "data/trailer_inspection_cron.xml",
        "views/trailer_standard_views.xml",
        "views/trailer_vin_views.xml",
        "views/trailer_equipment_views.xml",
        "views/trailer_inspection_views.xml",
        "views/trailer_quality_views.xml",
        "views/trailer_portal_templates.xml",
        "views/trailer_inspection_menus.xml",
        "report/trailer_inspection_paperformat.xml",
        "report/trailer_inspection_report.xml",
        "report/trailer_inspection_report_templates.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
