{
    'name': 'SaaS Lifecycle',
    'version': '19.0.1.0.0',
    'category': 'SaaS',
    'summary': 'Automated lifecycle management: dunning, churn, win-back',
    'author': 'ClickBuild',
    'website': 'https://clickbuild.com',
    'depends': ['saas_core'],
    'data': [
        'security/ir.model.access.csv',
        'data/saas_dunning_data.xml',
        'data/saas_lifecycle_rules_data.xml',
        'data/saas_lifecycle_cron.xml',
        'views/saas_cancellation_views.xml',
        'views/saas_dunning_views.xml',
        'views/saas_lifecycle_rule_views.xml',
        'views/saas_lifecycle_log_views.xml',
        'views/saas_lifecycle_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
