{
    'name': 'SaaS Notifications',
    'version': '19.0.1.0.0',
    'category': 'SaaS',
    'summary': 'Centralized multi-channel notification engine for ClickBuild',
    'author': 'ClickBuild',
    'website': 'https://clickbuild.com',
    'depends': ['saas_domain_manager', 'mail'],
    'data': [
        'security/saas_notifications_security.xml',
        'security/ir.model.access.csv',
        'data/saas_notification_types_data.xml',
        'data/saas_notification_templates_data.xml',
        'data/saas_notifications_cron.xml',
        'views/saas_notification_type_views.xml',
        'views/saas_notification_template_views.xml',
        'views/saas_notification_views.xml',
        'views/saas_sms_gateway_views.xml',
        'views/portal_notification_templates.xml',
        'views/saas_notifications_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
