{
    'name': 'SaaS Reporting & Analytics',
    'version': '19.0.1.0.0',
    'category': 'SaaS',
    'summary': 'MRR/ARR/LTV/Churn analytics',
    'author': 'ClickBuild',
    'website': 'https://clickbuild.com',
    'depends': ['saas_marketing'],
    'data': [
        'security/ir.model.access.csv',
        'data/saas_reporting_cron.xml',
        'views/saas_report_snapshot_views.xml',
        'views/saas_report_cohort_views.xml',
        'views/saas_reporting_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
