{
    'name': 'SaaS Support',
    'version': '19.0.1.0.0',
    'category': 'SaaS',
    'summary': 'Help desk: tickets, SLA tracking, assignment',
    'author': 'ClickBuild',
    'website': 'https://clickbuild.com',
    'depends': ['saas_reseller', 'mail'],
    'data': [
        'security/saas_support_security.xml',
        'security/ir.model.access.csv',
        'data/saas_ticket_sequence_data.xml',
        'data/saas_ticket_priorities_data.xml',
        'data/saas_ticket_categories_data.xml',
        'data/saas_ticket_sla_data.xml',
        'data/saas_support_cron.xml',
        'views/saas_ticket_category_views.xml',
        'views/saas_ticket_sla_views.xml',
        'views/saas_ticket_views.xml',
        'views/portal_support_templates.xml',
        'views/saas_support_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
