{
    'name': 'Saudi Restaurant Enterprise Demo',
    'version': '19.0.1.0.0',
    'category': 'Industries/Restaurants',
    'summary': 'Integrated Saudi restaurant operations and demo data',
    'author': 'Click Build Information Technology Company',
    'website': 'https://odoo.clickbulid.com',
    'depends': [
        'account_accountant',
        'approvals',
        'appointment',
        'delivery',
        'documents',
        'fleet',
        'helpdesk',
        'hr_appraisal',
        'hr_attendance',
        'hr_expense',
        'hr_holidays',
        'hr_payroll',
        'hr_recruitment',
        'l10n_sa_edi',
        'maintenance',
        'mrp_workorder',
        'mrp_product_expiry',
        'planning',
        'pos_loyalty',
        'pos_restaurant',
        'quality',
        'saas_demo_seed',
        'sale_loyalty',
        'sign',
        'stock_barcode',
        'stock_barcode_product_expiry',
        'product_expiry',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/restaurant_demo_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
