{
    'name': 'SaaS Marketplace',
    'version': '19.0.1.0.0',
    'category': 'SaaS',
    'summary': 'App marketplace: browse, install, and subscribe to add-ons',
    'author': 'ClickBuild',
    'website': 'https://clickbuild.com',
    'depends': ['saas_notifications'],
    'data': [
        'security/saas_marketplace_security.xml',
        'security/ir.model.access.csv',
        'data/saas_marketplace_categories_data.xml',
        'data/saas_marketplace_apps_data.xml',
        'data/saas_marketplace_cron.xml',
        'views/saas_marketplace_app_views.xml',
        'views/saas_tenant_app_views.xml',
        'views/portal_marketplace_templates.xml',
        'views/saas_marketplace_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
