{
    'name': 'SaaS Enterprise Demo Management',
    'version': '19.0.1.6.0',
    'category': 'SaaS',
    'summary': 'Enterprise demos with Telegram approvals and WhatsApp delivery',
    'author': 'Click Build Information Technology Company',
    'website': 'https://odoo.clickbulid.com',
    'depends': ['saas_website', 'mail', 'base_setup'],
    'data': [
        'security/saas_demo_security.xml',
        'security/ir.model.access.csv',
        'data/saas_demo_sequence.xml',
        'data/saas_demo_template_data.xml',
        'data/saas_demo_cron.xml',
        'views/saas_demo_request_views.xml',
        'views/saas_demo_template_views.xml',
        'views/saas_tenant_views.xml',
        'views/res_config_settings_views.xml',
        'views/website_demo_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'saas_demo_management/static/src/css/demo_request.css',
            'saas_demo_management/static/src/js/demo_status.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
