#!/bin/bash
# Sets up per-tenant nginx server blocks:
# 1. Creates /opt/odoo-saas/nginx-tenants/ on host
# 2. Mounts it as /etc/nginx/tenants/ in the nginx container
# 3. Adds `include /etc/nginx/tenants/*.conf;` to nginx.conf
# 4. Patches provision_tenant_cert.sh to write a tenant.conf after issuing a cert
# Idempotent.
set -e

TENANTS_DIR=/opt/odoo-saas/nginx-tenants
COMPOSE=/opt/odoo-saas/docker-compose.yml
NGINX_CONF=/opt/odoo-saas/config/nginx.conf
PROV_SCRIPT=/opt/odoo-saas/provision_tenant_cert.sh

mkdir -p "$TENANTS_DIR"
chmod 0755 "$TENANTS_DIR"

# 1. Mount into nginx container if not already mounted
if ! grep -q "nginx-tenants:/etc/nginx/tenants" "$COMPOSE"; then
    cp "$COMPOSE" "$COMPOSE.bak.tenantblocks.$(date +%s)"
    sed -i '/- \.\/certbot\/www:\/var\/www\/certbot:ro/a\      - ./nginx-tenants:/etc/nginx/tenants:ro' "$COMPOSE"
    echo "[tenant_blocks] added volume mount to docker-compose.yml"
    NEED_RECREATE=1
fi

# 2. Add include directive to nginx.conf (idempotent)
if ! grep -q "include /etc/nginx/tenants/" "$NGINX_CONF"; then
    cp "$NGINX_CONF" "$NGINX_CONF.bak.tenantblocks.$(date +%s)"
    # Insert just before the FIRST "server {" so includes get picked up
    python3 - "$NGINX_CONF" << 'PY'
import sys
p = sys.argv[1]
with open(p) as f: c = f.read()
inject = '\n    # Per-tenant server blocks (auto-generated by provision_tenant_cert.sh)\n    include /etc/nginx/tenants/*.conf;\n'
idx = c.find('    # HTTP: certbot + redirect to HTTPS')
assert idx != -1, 'could not find anchor in nginx.conf'
new = c[:idx] + inject + '\n' + c[idx:]
with open(p, 'w') as f: f.write(new)
print('[tenant_blocks] added include /etc/nginx/tenants/*.conf to nginx.conf')
PY
fi

# 3. Patch provision_tenant_cert.sh to write a tenant server block after issuing cert
if ! grep -q '# write per-tenant server block' "$PROV_SCRIPT" 2>/dev/null; then
    cp "$PROV_SCRIPT" "$PROV_SCRIPT.bak.$(date +%s)" 2>/dev/null || true
    python3 - "$PROV_SCRIPT" << 'PY'
import sys
p = sys.argv[1]
with open(p) as f: c = f.read()
# Insert before the final 'echo | openssl ...' verification line
anchor = '''echo "[provision] reloading nginx..."
docker exec odoo_saas_nginx nginx -t && docker exec odoo_saas_nginx nginx -s reload'''
new_block = '''# write per-tenant server block so nginx serves the new cert under SNI
TENANTS_DIR=/opt/odoo-saas/nginx-tenants
mkdir -p "$TENANTS_DIR"
cat > "$TENANTS_DIR/$SUB.conf" << TENANT
# Auto-generated by provision_tenant_cert.sh on $(date -Is)
server {
    listen 443 ssl http2;
    server_name $FQDN;

    ssl_certificate     /etc/letsencrypt/live/$FQDN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$FQDN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    client_max_body_size 200m;
    proxy_read_timeout 720s;

    location /websocket {
        proxy_pass http://odoo_longpolling;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \\\$http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \\\$host;
        proxy_set_header X-Forwarded-Proto https;
    }
    location /longpolling {
        proxy_pass http://odoo_longpolling;
        proxy_set_header Host \\\$host;
        proxy_set_header X-Forwarded-Proto https;
    }
    location / {
        proxy_pass http://odoo_backend;
        proxy_set_header Host \\\$host;
        proxy_set_header X-Real-IP \\\$remote_addr;
        proxy_set_header X-Forwarded-For \\\$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
        proxy_buffering off;
    }
}
TENANT
echo "[provision] wrote nginx tenant block: $TENANTS_DIR/$SUB.conf"

'''
c = c.replace(anchor, new_block + anchor)
with open(p, 'w') as f: f.write(c)
print('[tenant_blocks] patched provision_tenant_cert.sh')
PY
fi

# 4. Recreate nginx container if needed (to pick up new volume mount)
if [ "$NEED_RECREATE" = "1" ]; then
    echo "[tenant_blocks] recreating nginx container to pick up new volume..."
    cd /opt/odoo-saas && docker compose up -d nginx
    sleep 3
fi

echo "[tenant_blocks] testing nginx..."
docker exec odoo_saas_nginx nginx -t 2>&1 | grep -vE 'deprecated' | tail -3

echo "[tenant_blocks] done"
ls -la "$TENANTS_DIR" 2>/dev/null
