{
    'name': 'SaaS Tenant Manager',
    'version': '19.0.1.0.0',
    'category': 'Administration',
    'summary': 'Multi-tenant SaaS management for Odoo',
    'description': 'Complete SaaS management module for Odoo Community.',
    'author': 'SaaS Platform',
    'website': 'https://odoo.clickbulid.com',
    'depends': ['base', 'mail', 'web'],
    'data': [
        'security/saas_security.xml',
        'security/ir.model.access.csv',
        'data/saas_plan_data.xml',
        'data/saas_cron.xml',
        'views/saas_plan_views.xml',
        'views/saas_backup_views.xml',
        'views/saas_tenant_views.xml',
        'wizards/create_tenant_wizard.xml',
        'views/saas_menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'images': ['static/description/icon.png'],
}
