{
    'name': 'SaaS Billing',
    'version': '19.0.1.0.0',
    'category': 'SaaS',
    'summary': 'Invoice engine, PDF generation, VAT/tax management, credit notes',
    'author': 'ClickBuild',
    'website': 'https://clickbuild.com',
    'depends': ['saas_subscription'],
    'data': [
        'security/ir.model.access.csv',
        'data/saas_invoice_sequence.xml',
        'data/saas_tax_data.xml',
        'data/saas_billing_cron.xml',
        'report/invoice_report_action.xml',
        'report/invoice_template.xml',
        'views/saas_tax_rate_views.xml',
        'views/saas_invoice_views.xml',
        'views/saas_credit_note_views.xml',
        'views/saas_billing_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
