{
    'name': 'SaaS Subscription',
    'version': '19.0.1.2.0',
    'category': 'SaaS',
    'summary': 'Subscription management: upgrades, downgrades, proration, renewals',
    'author': 'ClickBuild',
    'website': 'https://clickbuild.com',
    'depends': ['saas_lifecycle'],
    'data': [
        'security/ir.model.access.csv',
        'data/saas_subscription_cron.xml',
        'views/saas_subscription_history_views.xml',
        'views/saas_plan_change_views.xml',
        'views/saas_subscription_views.xml',
        'views/saas_subscription_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
